Bus Express Web-Service/BusExpress.PL/Models/Project/OrderInfo.cs
namespace BusExpress.PL.Models
{
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrderInfos")]
    public class OrderInfo
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string LName_FName { get; set; }
        public int PlaceNumber { get; set; }
        public string Phone { get; set; }
        public string OrderNumber { get; set; }
        public string MoneyAmount { get; set; }

        public override string ToString()
        {
            return $"{Id}{From}{To}{LName_FName}{PlaceNumber}" +
                   $"{Phone}{OrderNumber}{MoneyAmount}";
        }
    }
}

Bus Express Web-Service/BusExpress.PL/Models/Project/PassInfo.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace BusExpress.PL.Models
{
    [Table("PassInfos")]
    public class PassInfo // : Interfaces.IEntity
    {
        public int Id { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public string Booking_Route { get; set; }
        public int Qty { get; set; }
        public string Tax { get; set; }
        public string Total { get; set; }
        public string Payment_Method { get; set; }
        public string C_FName { get; set; }
        public string C_LName { get; set; }
        public string C_Phone { get; set; }
        public string C_Email { get; set; }
        public string C_Notes { get; set; }

        public override string ToString()
        {
            return $"{Id}{Booking_Date}{Booking_Route}{Qty}{Tax}" +
                   $"{Total}{Payment_Method}{C_FName}{C_LName}" +
                   $"{C_Phone}{C_Email}{C_Notes}";
        }
    }
}

Bus Express Web-Service/BusExpress.PL/Controllers/DetailsController.cs
namespace BusExpress.PL.Controllers
{
    using BusExpress.BLL.Interfaces;
    using BusExpress.BLL.Services;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Linq;

    public class DetailsController : Controller
    {
        private readonly IBusExpressService service;

        public DetailsController()
        {
            service = new BusExpressService(Models.Init.GetConnectStr);
        }

        public async Task<ActionResult> PassInfo(int? id)
        {
            if (id == null) return HttpNotFound();
            var found = await service.ReadPassengersAsync();
            return View(found.FirstOrDefault(i => i.Id == id));
        }

        public async Task<ActionResult> OrderInfo(int? id)
        {
            if (id == null) return HttpNotFound();
            var found = await service.ReadOrderInfosAsync();
            return View(found.FirstOrDefault(i => i.Id == id));
        }
    }
}

Bus Express Web-Service/BusExpress.PL/Controllers/SelectController.cs
namespace BusExpress.PL.Controllers
{
    using System.Collections.Generic;
    using BusExpress.BLL.Interfaces;
    using BusExpress.BLL.Services;
    using System.Threading.Tasks;
    using BusExpress.BLL.Dto;
    using System.Web.Mvc;
    using OfficeOpenXml;
    using System.Linq;
    using System.Web;
    using System.IO;
    using System;

    public enum MsgType
    {
        Empty,
        Error,
        BusyPls,
        Success
    }

    public class SelectController : Controller
    {
        private readonly IBusExpressService service;
        private static bool IsEmpty { get; set; } = false;
        private static bool IsImport { get; set; } = false;
        public static bool IsBusyPlace { get; set; } = false;
        public static IEnumerable<IModel> FromEXCLToList { get; set; } = default;

        public SelectController()
        {
            service = new BusExpressService(Models.Init.GetConnectStr);
            if (FromEXCLToList != default) ImportExecute();
        }

        #region Passangers Info:
        public ActionResult PassInfo()
        {
            var lst = IsImport ? FromEXCLToList : service.ReadPassengers().ToList();
            if (!lst.Any())
            {
                IsEmpty = true;
                ViewBag.EmptyMsg = GetMessage(MsgType.Empty);
            }
            ViewBag.IsEmpty = IsEmpty;
            return View(lst);
        }

        [HttpPost]
        public ActionResult PassInfoView()
        {
            return View();
        }       
        #endregion

        #region Order Info:
        public ActionResult OrderInfo()
        {
            var lst = IsImport ? FromEXCLToList : service.ReadOrderInfos().ToList();
            if (!lst.Any())
            {
                IsEmpty = true;
                ViewBag.EmptyMsg = GetMessage(MsgType.Empty);
            }
            ViewBag.IsEmpty = IsEmpty;
            return View(lst);
        }

        [HttpPost]
        public ActionResult OrderInfo(OrderInfoDto oi)
        {
            return View();
        }
        #endregion

        #region Schema Places Info:
        public ActionResult SchemaPlacesInfo()
        {
            var spi = service.ReadSchemaPlaces().ToList();
            return View(spi[0]);
        }

        [HttpPost]
        public ActionResult SchemaPlacesInfo(SchemaPlaceDto o)
        {
            var button =
               Request.Params.Cast<string>().Where(p => p.StartsWith("btn")).Select(p => p.Substring("btn".Length)).First().Remove(0, 1);
            if (button == "busy") 
            { IsBusyPlace = true; ViewBag.BusyMsg = GetMessage(MsgType.BusyPls); }
            else
            {
                return RedirectToAction("OrderInfo", "Create", new { fillPlace = button });
                    //RedirectToAction($"../Create/OrderInfo/fillPlace={button}");
            }
            var spi = service.ReadSchemaPlaces().ToList();
            return View(spi[0]);
        }
        #endregion

        #region Destinations Info
        public ActionResult DestinationInfo()
        {
            var lst = IsImport ? FromEXCLToList : service.ReadDestinations().ToList();
            if (!lst.Any())
            {
                IsEmpty = true;
                ViewBag.EmptyMsg = GetMessage(MsgType.Empty);
            }
            ViewBag.IsEmpty = IsEmpty;
            return View(lst);
        }

        [HttpPost]
        public ActionResult DestinationInfo(DestinationDto di)
        {
            return View();
        }
        #endregion

        public ActionResult CloseAlerts()
        {
            IsBusyPlace = false;
            return RedirectToAction("../Select/SchemaPlacesInfo");
        }

        private string GetMessage(MsgType type)
        {
            switch (type)
            {
                case MsgType.Empty:
                    return "The table list is empty... Try to fill it in!";
                case MsgType.Success:
                    return "";
                case MsgType.Error:
                    return "";
                case MsgType.BusyPls:
                    return "This place are Busy...";
                default:
                    return "NaN";
            }
        }

        private ActionResult ImportExecute()
        {
            IsImport = true;
            var entityType = FromEXCLToList.GetType().GetGenericArguments()[0];
            switch (entityType.Name)
            {
                case nameof(PassInfoDto):
                    return RedirectToAction("PassInfo");
                case nameof(OrderInfoDto):
                    return RedirectToAction("OrderInfo");
                case nameof(DestinationDto):
                    return RedirectToAction("DestinationInfo");
                default: return RedirectToAction("../Shared/Error");
            }
        }
    }
}

Bus Express Web-Service/BusExpress.PL/Views/Details/OrderInfo.cshtml
@model BusExpress.BLL.Dto.OrderInfoDto

@{
    ViewBag.Title = "Order Info Details";
}

<hr />
<h2 style="text-align:center;color:blue;font-family:'Palatino Linotype';font-weight:bold">
    <span style="background-color:black;color:white;padding:12px">
        Order Info - [Details Form]
    </span>
</h2>
<hr />

<div class="row" style="text-align:center">
    <div class="col">
        <dl id="scope" class="dl-horizontal">
            <dt>
                <label style="text-align:left">Id:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Id, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>From:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.From, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>To:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.To, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Last & First Name:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.LName_FName, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Number Place:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.PlaceNumber, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Phone:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Phone, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Order Number:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.OrderNumber, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Money Amount:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.MoneyAmount, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Is Ordered?:</label>
            </dt>
            <dd>
                @{
                    var isordered = Model.IsOrdered == false ? "YES" : "No";
                }
                <input id = "val_field" value="@isordered" readonly /> 
            </dd>
        </dl>
    </div>
</div>

<div style="text-align:center;margin-top:15px">
    @Html.ActionLink("Back to List", "OrderInfo", "Select", null, new { style = "", @class = "btn btn-danger" })
</div>


<style>
    dt {
        color: darkred;
        text-align: left;
    }

    #scope {
        width: 300px;
        margin: auto;
        padding: 22px;
        background-image: linear-gradient(black, yellow, darkgray)
    }

    #val_field {
        text-align: left;
        background-color: black;
        text-align: center;
        font-family: palatino linotype;
        font-weight: bold;
        color: darkorange;
        font-size: large
    }
</style>

Bus Express Web-Service/BusExpress.PL/Views/Details/PassInfo.cshtml
@model BusExpress.BLL.Dto.PassInfoDto

@{
    ViewBag.Title = "Pass Info Details";
}

<hr />
<h2 style="text-align:center;color:blue;font-family:'Palatino Linotype';font-weight:bold">
    <span style="background-color:black;color:white;padding:12px">
        Passenger Info - [Details Form]
    </span>
</h2>
<hr />

<div class="row" style="text-align:center">
    <div class="col">
        <dl id="scope" class="dl-horizontal">
            <dt>
                <label style="text-align:left">Id:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Id, new { id = "val_field", @readonly=true })
            </dd>

            <dt>
                <label>Booking Date:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Booking_Date, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Booking Route:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Booking_Route, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Quantity:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Qty, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Tax:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Tax, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Total:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Total, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Payment Method:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.Payment_Method, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>First Name:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.C_FName, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Last Name:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.C_LName, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Phone:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.C_Phone, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Email:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.C_Email, new { id = "val_field", @readonly = true })
            </dd>

            <dt>
                <label>Notes:</label>
            </dt>

            <dd>
                @Html.TextBoxFor(model => model.C_Notes, new { id = "val_field", @readonly = true })
            </dd>

        </dl>
    </div>
</div>

<div style="text-align:center;margin-top:15px">
    @Html.ActionLink("Back to List", "PassInfo", "Select", null, new { style = "", @class = "btn btn-danger" })
</div>


<style>
    dt{
        color:darkred;
        text-align:left;
    }
    #scope {      
        width:300px;
        margin:auto;
        padding: 22px;
        background-image: linear-gradient(black, yellow, darkgray)
    }
    #val_field {
        text-align: left;
        background-color: black;
        text-align: center;
        font-family: palatino linotype;
        font-weight:bold;
        color:darkorange;
        font-size: large
    }
</style>