Bus Express Web-Service/BusExpress.PL/Controllers/StreamController.cs
namespace BusExpress.PL.Controllers
{
    using Models;
    using System;
    using System.IO;
    using System.Web;
    using System.Linq;
    using OfficeOpenXml;
    using System.Web.Mvc;
    using BusExpress.BLL.Dto;
    using BusExpress.BLL.Interfaces;
    using System.Web.UI.WebControls;
    using System.Collections.Generic;

    public class StreamController : Controller
    {
        private string model;
        private readonly ExcelLogic exl; 
        private string Path { get; set; }

        public StreamController()
        {
            exl = new ExcelLogic();
        }

        [HttpGet]
        public ActionResult Import(string model)
        {
            this.model = model;
            ViewBag.Entity = GetEntityName(model);
            return View();
        }

        [HttpPost]
        public ActionResult Import()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            HttpPostedFileBase file = Request.Files[0];
            UploadToMainDir(file);
            using (ExcelPackage package = new ExcelPackage(new FileInfo(Path)))
            {
                var sheet = package.Workbook.Worksheets.FirstOrDefault();
                SelectController.FromEXCLToList = GetList(sheet, model);
            }
            return RedirectToAction($"../Select/PassInfo");
        }


        [HttpGet]
        public ActionResult Uploded(string view)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Uploded()
        {
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.  
                        Path = System.IO.Path.Combine(Server.MapPath($"~/Uploaded_Files/{fname}"));
                        file.SaveAs(Path);
                    }
                    // Returns message that successfully uploaded  
                    return Json("Your file was uploaded successfully!");
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("There was no file selected. Please try again.");
            }
        }

        #region Show All Files & Delete selected file:
        public ActionResult AllFiles()
        {
            var names = new List<string>();
            Path = Server.MapPath("~/Uploaded_Files");
            string[] files_names = Directory.GetFiles(Path, "*", SearchOption.AllDirectories);
            for (int i = 0; i < files_names.Length; i++)
                names.Add(System.IO.Path.GetFileName(files_names[i]));

            return View(names);
        }
        #endregion

        #region Delete file:
        public ActionResult DeleteFile(string item)
        {
            var flag = false;
            if (item != null)
            {
                flag = true;
                var path = System.IO.Path.Combine(Server.MapPath($"~/Uploaded_Files/{item}"));
                System.IO.File.Delete(path);
            }
            if (!flag) return Json("There is nothing to delete...Please upload a file first.");
            else return RedirectToAction("../Stream/AllFiles");
        }
        #endregion

        private void UploadToMainDir(HttpPostedFileBase file)
        {
            string fname;
            if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
            {
                string[] testfiles = file.FileName.Split(new char[] { '\\' });
                fname = testfiles[testfiles.Length - 1];
            }
            else fname = file.FileName;
            Path = System.IO.Path.Combine(Server.MapPath($"~/Uploaded_Files/{fname}"));
            file.SaveAs(Path);
        }

        #region Auxiliary Methods:
        private IEnumerable<IModel> GetList(ExcelWorksheet sheet, string model)
        {
            switch (model)
            {
                case nameof(PassInfoDto):
                    return exl.GetList<PassInfoDto>(sheet).ToList();
                case nameof(OrderInfoDto):
                    return exl.GetList<OrderInfoDto>(sheet).ToList();
                case nameof(DestinationDto):
                    return exl.GetList<DestinationDto>(sheet).ToList();
                default: return new List<IModel>();
            }
        }

        private string GetEntityName(string model)
        {
            switch (model)
            {
                case nameof(PassInfoDto):
                    return "Passenger Info";
                case nameof(OrderInfoDto):
                    return "Order Info";
                case nameof(DestinationDto):
                    return "Destination Info";
                default: return string.Empty;
            }
        }
        #endregion
    }
}

Bus Express Web-Service/BusExpress.PL/Views/Stream/AllFiles.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "All Files";
}


<h1 style="color:darkorange;font-weight:bold;text-align:center">All Uploaded Files</h1>

@if (Model == null)
{
    <div id="frame">
        <h5 style="color:red;font-family:'Palatino Linotype';text-align:center">
            There is no File that has been uploaded yet.
        </h5>
    </div>
}
else
{
    using (Html.BeginForm())
    {
        foreach (var item in Model)
        {
            <div id="frame">
                <a style="margin:0 0 0 40px" id="itm" href="~/Uploaded_Files/@item">@item</a>
                @Html.ActionLink($"Delete", "DeleteFile", "Stream", new { item = item }, new { id = "filename", onclick = "return confirm('Are you sure you want to delete this File?');" })
                <br />
            </div>
        }
    }
}
<br />
<br />
<br />

@*<div id="back_btn">
          @Html.ActionLink("<-- Go Back", "Index", "Home", "", new { id = "back" })
    </div>'
*@
<p></p>
<p></p>
<p></p>
<p></p>

<style>
    #back_btn {
        width: 120px;
        margin: auto;
    }

    #back {
        border: 1px solid blue;
        border-radius: 15px;
        text-decoration: none;
        color: blue;
        padding: 13px;
    }

        #back:hover {
            background-color: blue;
            color: white;
            font-weight: bold;
        }

    #itm {
        font-size: large;
    }

    #frame {
        border: 0.5px solid blue;
        border-radius: 9px;
        padding: 22px;
        margin-top: 5px;
    }

    #filename {
        margin: -7px 0 0 0;
        float: left;
        text-decoration: none;
        border: 1px solid red;
        border-radius: 18px;
        padding: 6px;
        color: white;
        background-color: red;
        font-size: larger;
    }

        #filename:hover {
            border: 1px solid red;
            background-color: white;
            color: red;
        }
</style>

Bus Express Web-Service/BusExpress.PL/Views/Stream/Import.cshtml
@model string
@{
    ViewBag.Title = "Import " + ViewBag.Entity;
}

<h2 id="title">
    <span id="sp">
        Import any Excel file with @ViewBag.Entity
    </span>
</h2>
@using (@Html.BeginForm("Import", "Stream", FormMethod.Post, new { @id = "form1", @enctype = "multipart/form-data" }))
{
    <div class="row" style="text-align:center">
        <div class="col"></div>
        <div class="col" id="upl">
            <h2>File type: .xlsx | csv</h2>
            <input type="file" class="btn btn-danger" name="file_Uploader" /><br /><br />
            <input type="submit" class="btn btn-primary" id="btn_Upload" value="Upload" />
        </div>
        <div class="col"></div>
    </div>
}

<style>
    #title {
        font-family: 'Palatino Linotype';
        font-weight: bold;
        color: yellow;
        text-align: center;
        margin-top:17px
    }
    #sp {
        padding: 7px;
        border-radius: 5px;
        background-color: blue
    }
    #upl {
        padding: 62px;
        border: 0.1px solid;
        border-radius: 5px;
        margin-top: 12px;
        background-color: black
    }
</style>

Bus Express Web-Service/BusExpress.PL/Views/Stream/Uploded.cshtml
@{
    ViewBag.Title = "Upload Any File";
}

<h3 style="text-align:center;color:darkblue;margin-top:22px;font-family:'Palatino Linotype'">
    Upload any file the following formats (.pdf, .doc, .docs, .docx, .csv, .xls, .xlsx)
</h3>

<div class="row" style="text-align:center">
    <div id="file_upl" class="col-md-5">
        <input id="fileinput" type="file" accept=".pdf, .doc, .docs, .docx, .csv, .xls, .xlsx">

        <script type="text/javascript">
            var fileInput = document.getElementById("fileinput");
            var allow1 = ".pdf";
            var allow2 = ".doc";
            var allow3 = ".docs";
            var allow4 = ".docx";
            var allow5 = ".csv";
            var allow6 = ".xls";
            var allow7 = ".xlsx";
            fileInput.addEventListener("change", function () {
                // Check that the file extension is supported.
                // If not, clear the input.
                var hasInvalidFiles = false;
                for (var i = 0; i < this.files.length; i++) {
                    var file = this.files[i];
                    if (!file.name.endsWith(allow1) && !file.name.endsWith(allow2) && !file.name.endsWith(allow3) &&
                        !file.name.endsWith(allow4) && !file.name.endsWith(allow5) && !file.name.endsWith(allow6) &&
                        !file.name.endsWith(allow7)) {
                        hasInvalidFiles = true;
                    }
                }
                if (hasInvalidFiles) {
                    fileInput.value = "";
                    alert("Unsupported file type was selected.");
                }
            });
        </script>

        <br />
        <input type="button" id="btnUpload" value="Upload File/s" />

        <h5 style="color:green;font-family:'Palatino Linotype'"> @ViewBag.UploadMsg</h5>
        <br />
        @Html.ActionLink("See All Uploaded Files", "AllFiles", "Stream", "", new { @class = "btn btn-primary" })
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
                    $(document).ready(function () {
                        $('#btnUpload').click(function () {
                            // Checking whether FormData is available in browser
                            if (window.FormData !== undefined) {
                                var fileUpload = $("#fileinput").get(0);
                                var files = fileUpload.files;
                                // Create FormData object
                                var fileData = new FormData();
                                // Looping over all files and add it to FormData object
                                for (var i = 0; i < files.length; i++) {
                                    fileData.append(files[i].name, files[i]);
                                }
                                $.ajax({
                                    url: '/Stream/Uploded',
                                    type: "POST",
                                    contentType: false,
                                    processData: false,
                                    data: fileData,
                                    success: function (result) {
                                        alert(result);
                                    },
                                    error: function (err) {
                                        alert(err.statusText);
                                    }
                                });
                            } else {
                                alert("FormData is not supported.");
                            }
                        });
                    });
</script>


<style>
    #file_upl {
        border: 0.1px solid black;
        margin: auto;
        width: 450px;
        border-radius: 15px;
        padding: 35px;
    }
</style>